import { Metadata } from "next";
import { Poppins } from "next/font/google";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });
export const metadata: Metadata = {
  title: "Welcome to, Neakhatka.com",
  description: "Generated by create next app",
};
const LoginLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <link rel="icon" href="/logo.svg" />
      <body className={poppins.className}>
        <section>{children}</section>
      </body>
    </html>
  );
};

export default LoginLayout;
