import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import {Sidebar} from "@/components";
import { ThemeProvider } from "@/components/theme/Provider";
import { NavDashboard } from "@/components/organisms/NavDashboard/NavDashboard";
const poppins = Poppins({ subsets: ["latin"], weight: "400" });


export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} flex item-center justify-between`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Sidebar />
          <main className="w-screen h-screen">
            <NavDashboard />
            <div>{children}</div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}

