import { Poppins } from "next/font/google";
import Nav from "@/components/organisms/Navbar/Nav";
import { Footer } from "@/components";
import { Metadata } from "next";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });
export const metadata: Metadata = {
  title: "Create an Account, Neakhatka.com",
  description: "Generated by create next app",
};
const JoinLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <link rel="icon" href="/logo.svg" />
      <body className={poppins.className}>
        <section>{children}</section>
      </body>
    </html>
  );
};

export default JoinLayout;
