import CardContext from "@/contexts/CardInfoContext";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <CardContext>{children}</CardContext>
      </body>
    </html>
  );
}
